### ISSUE TITLE
clicking the link for the GH project for Countries and Capitals brings me to Baskteball app

### ISSUE THREAD

**Issue by aric87** [mse2321/marcus-eubanks-portfolio#1]
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/js/me_innovation.js#L29
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/js/me_innovation.js#L30
these two have the links switched

**Comment by mse2321** [comment]
Yeah, dumb mistake. I fixed it. Will push live later on.
