### ISSUE TITLE
background-color transparent?

### ISSUE THREAD

**Issue by aric87** [mse2321/marcus-eubanks-portfolio#13]
Why not just set to none? 
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/css/style.scss#L136

**Comment by mse2321** [comment]
I wanted it to match the background color of the body.

**Comment by aric87** [comment]
if there's no background, it's going to _be_ the color of the body.

**Comment by mse2321** [comment]
True, so I'll just make it white and call it a day.
