### ISSUE TITLE
why so much duplication? 

### ISSUE THREAD

**Issue by aric87** [mse2321/marcus-eubanks-portfolio#14]
try to refactor these queries so there's no so much copied between them
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/css/style.scss#L199
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/css/style.scss#L207

**Comment by mse2321** [comment]
Ok I will take a look and see what I can remove

**Comment by mse2321** [comment]
I cleaned up the last two queries that you mentioned. The rest have to remain as is since, they are different from the default styles.

**Comment by mse2321** [comment]
All set
