### ISSUE TITLE
the about me looks odd on desktop

### ISSUE THREAD

**Issue by aric87** [mse2321/marcus-eubanks-portfolio#15]
<img width="1383" alt="screen shot 2016-09-20 at 11 12 04 am" src="https://cloud.githubusercontent.com/assets/9463572/18676309/2c6ed5e6-7f23-11e6-9521-d2a44847249c.png">
It shouldn't be wayyy left aligned, because it looks like there's supposed to be something to the right of it.

**Comment by mse2321** [comment]
Yeah it was left aligned by design, but I agree that it should be centered.

**Comment by mse2321** [comment]
Done. I like it a lot better this way. I also adjusted the gallery-data section as well.
