### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by aric87** [mse2321/marcus-eubanks-portfolio#16]
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/index.html#L34

**Comment by aric87** [comment]
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/index.html#L42

**Comment by aric87** [comment]
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/index.html#L90

**Comment by mse2321** [comment]
Not sure how this happened, but fixing it now.

**Comment by mse2321** [comment]
Done
