### ISSUE TITLE
seems to be dupliacted

### ISSUE THREAD

**Issue by aric87** [mse2321/marcus-eubanks-portfolio#4]
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/index.html#L40
Not sure why the social icons are duplicated. I don't see this section ever being shown on your portfolio

**Comment by mse2321** [comment]
The second set of contact icons are used for mobile navigation I believe. That set moves over to the nav sidebar in mobile views. I can try and figure out a better way to do this.

**Comment by aric87** [comment]
unless it's on really small browsers, those are currently not displaying ever

**Comment by mse2321** [comment]
I just checked it and I see an issue with it. I will just remove the second set.

**Comment by mse2321** [comment]
Done
