### ISSUE TITLE
run ng-repeat once

### ISSUE THREAD

**Issue by aric87** [mse2321/marcus-eubanks-portfolio#5]
here: https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/index.html#L93
You're iterating through items 3 times, should only be once. 

<div class="meta_wrap" >
  <div ng-repeat="item in items">
	<div class="art_title"  ng-hide="!newIndex($index)"><h2>{{ item.title }}</h2></div>
	<div class="subdata" id="desc" ng-hide="!newIndex($index)">{{ item.desc }}</div>
	<div class="subdata" id="tech"  ng-hide="!newIndex($index)">{{ item.tech }}</div>
  </div>
</div>

**Comment by mse2321** [comment]
I believe I can set the ng-repeat on the wraps and set to limit 1? Otherwise I will get 4 copies of each wrap for each item in the array.

**Comment by aric87** [comment]
using ng-repeat with a limit of 1 is the same as not using ng-repeat

**Comment by aric87** [comment]
```<div class="meta_wrap">
        <div ng-repeat="item in items">
							<div class="art_title"  ng-hide="!newIndex($index)"><h2>{{ item.title }}</h2></div>
							<div class="subdata" id="desc"  ng-hide="!newIndex($index)">{{ item.desc }}</div>
							<div class="subdata" id="tech" ng-hide="!newIndex($index)">{{ item.tech }}</div>
</div>
						</div>```

**Comment by mse2321** [comment]
Oh okay, I see. Done.
