### ISSUE TITLE
nullifying the use of ng-repeat here

### ISSUE THREAD

**Issue by aric87** [mse2321/marcus-eubanks-portfolio#6]
You're using ng-repeat, but stopping it at one, then hardcoding the headings and attributes for each item in stats. 

https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/index.html#L116

Either remove the limit, the 2nd and 3rd harcoded stats_col's and move the repeat to the stats_col, or remove the ng-repeat.

**Comment by mse2321** [comment]
Done. Removed the limit and the ng-repeat
