### ISSUE TITLE
not sure what this is doing

### ISSUE THREAD

**Issue by aric87** [mse2321/marcus-eubanks-portfolio#7]
I don't see what this is for, but you should make these three funcitons into 1, and pass a paramter if you need to keep it. 
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/js/me_innovation.js#L14

**Comment by mse2321** [comment]
This is to display the correct stats under each section. Can refactor into one function and possibly also refactor the stats_wrap code to ng-repeat for each stat and use the function to set the icon.

**Comment by mse2321** [comment]
I refactored into a single function passing in the values. Done
