### ISSUE TITLE
comment is incorrect

### ISSUE THREAD

**Issue by aric87** [mse2321/marcus-eubanks-portfolio#8]
The comment says this sets the value, but it's comparing, and will return true/false. 
comment should reflect that.
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/js/me_innovation.js#L39

**Comment by mse2321** [comment]
That comment is only referring to line 40. I will comment the rest of it so it makes more sense. I fixed some code in that as well.

**Comment by mse2321** [comment]
I just removed the comment.
