### ISSUE TITLE
dump jQuery

### ISSUE THREAD

**Issue by aric87** [mse2321/marcus-eubanks-portfolio#9]
You shouldn't load jQuery for a simple animation. grab the relevant code from jQuery if you need to, but don't use the whole lib. 
https://github.com/mse2321/marcus-eubanks-portfolio/blob/master/js/me_innovation.js#L64

**Comment by mse2321** [comment]
Ok, I will work on this

**Comment by mse2321** [comment]
What is the best approach, using vanilla js or trying to find a way to do this with Angular?

**Comment by mse2321** [comment]
Nevermind. I just used vanilla JS

**Comment by aric87** [comment]
try and use angular animations if you can

**Comment by mse2321** [comment]
What do you mean by relevant code from jQuery? I haven't found any solutions yet that would work for this situation. Most of what I have seen works off of an ng-click. I need the toggle to occur only when the screen size is less than 899px. I tried ng-show, but that did not work. It's crazy that angular does not have a ng-toggle directive. I know it's not the best practice, but unless I can find an example of another solution, I am going to have to keep the code as is.

**Comment by mse2321** [comment]
ngAnimate should get the job done. Didn't work correctly on my first attempt for some reason. Will revisit.

**Comment by mse2321** [comment]
I've tried several times and can't get ngAnimate the load on the app. Could you review it? I can't figure out what is wrong.

**Comment by mse2321** [comment]
Done. Used CSS3 transitions instead.
